Enable file selection on moved files and folders on samba shares
mate-desktop/caja pull request #1375
Opened 2020-04-23 15:26 UTC by echo083

The call to the methode caja_file_changes_queue_file_moved prevents the selection on moved files and folders on samba shares.
I'm not a gtk expert and don't understand clearly the cause. Replacing caja_file_changes_queue_file_moved by a call to caja_file_changes_queue_file_removed and caja_file_changes_queue_file_added works and should have the same behavior.

2020-04-27 10:35 UTC, raveit65 commented
I am using only nfs shares.
@mate-desktop/core-team 
Does anyone use samba shares from  the team for testing?

2020-04-27 12:37 UTC, lukefromdc commented
I use neither one myself.

On 4/27/2020 at 5:35 AM, "raveit65"  wrote:
	I am using only nfs shares.
 @mate-desktop/core-team
 Does anyone use samba shares from  the team for testing? 

	—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-04-27 14:28 UTC, echo083 commented
> The description is wrong, since it's not only applied to remote files. It goes without saying that your proposal has an overstrain on local file systems.

Hello,

You are right, my modification request also impacts the local file systems for move actions, but it's because after a move action is done, the method caja_file_changes_consume_changes is called which calls the methods caja_directory_notify_files_* depending of the elements in the caja files queue (CajaFileChangesQueue singleton) and triggers many signals. I'm afraid that if we don't apply the same logic for local file systems and remote file systems we would encounter unexpected side effects very difficult to understand. So my recommendation is to apply my proposal as it is or not at all.

Also I'm looking forward anybody to reproduce the bug and check that with my modification proposal fixes it. For information the fie I modified shares the same logic as this file in the nautilus project https://github.com/GNOME/nautilus/blob/mainline/src/nautilus-file-operations.c and I had the same bug but I didn't recompile it with my modification. Maybe I could request a review on their side too. What's your opinion?

Thanks

2020-04-27 17:17 UTC, lukefromdc commented
On the one hand, we cannot afford to make caja too heavy for old/small
systems to handle, or even worse import the bugs we have (freezes etc)
on remote mounts that bog down or disappeae to local filesystem
handling. If this requires limiting features on remote filesystem
management I'm in favor of so doing
On the other hand, Nautilus (from which caja was forked) was
originally intended right from the start to handle both local and
remote filesystwms

On 4/27/2020 at 9:28 AM, "echo083"  wrote:
	The description is wrong, since it's not only appliedo  to remote
files. It goes without saying that your proposal has an overstrain on
local file systems.  

	Hello, 

	You are right, my modification request also impacts the local file
systems for move actions, but it's because after a move action is
done, the method caja_file_changes_consume_changes is called which
calls the methods caja_directory_notify_files_* depending of the
elements in the caja files queue (CajaFileChangesQueue singleton) and
triggers many signals. I'm afraid that if we don't apply the same
logic for local file systems and remote file systems we would
encounter unexpected side effects very difficult to understand. So my
recommendation is to apply my proposal as it is or not at all. 

	Also I'm looking forward anybody to reproduce the bug and check that
with my modification proposal fixes it. For information the fie I
modified shares the same logic as this file in the nautilus project
https://github.com/GNOME/nautilus/blob/mainline/src/nautilus-file-operations.c
and I had the same bug but I didn't recompile it with my modification.
Maybe I could request a review on their side too. What's your opinion?


	Thanks 

	—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-25 23:01 UTC, lukefromdc commented
Any updates on this

2020-12-27 15:15 UTC, echo083 commented
> Any updates on this

Hello,

Since 23.04 I'm using caja with my patch and didn't get any issue and I'm using it to move files on a daily basis si I'm quite confident of the reliability of my pull request. However a single proof of work is not sufficient in my opinion, except if you are voluntary to recompile caja and apply my patch and test it for a while on your own. You would require a samba share for information.

Thanks

2020-12-27 17:44 UTC, raveit65 commented
> > Any updates on this
> 
> Hello,
> 
> Since 23.04 I'm using caja with my patch and didn't get any issue and I'm using it to move files on a daily basis si I'm quite confident of the reliability of my pull request. However a single proof of work is not sufficient in my opinion, except if you are voluntary to recompile caja and apply my patch and test it for a while on your own. You would require a samba share for information.
> 
> Thanks

Since April there is a change request.......

2022-08-04 18:56 UTC, lukefromdc commented
Any updates on this or should we close it?

2022-08-05 08:37 UTC, echo083 commented
Hello, I'm still using my patch since April 2020 and had no issue. I requested a review, now proceed as you want if you know a developer or you are able yourself to review it and decide if it can be integrated to the main branch please go ahead otherwise you can close it.
Thanks

2022-08-05 09:13 UTC, rbuj requested changes
I don't agree with removing the function **caja_file_changes_queue_file_moved** and the operation kind **CHANGE_FILE_MOVED**.
```
$ git grep caja_file_changes_queue_file_moved
libcaja-private/caja-file-changes-queue.c:caja_file_changes_queue_file_moved (GFile *from,
libcaja-private/caja-file-changes-queue.h:void caja_file_changes_queue_file_moved                      (GFile      *from,
```
```
$ git grep CHANGE_FILE_MOVED
libcaja-private/caja-file-changes-queue.c:    CHANGE_FILE_MOVED,
libcaja-private/caja-file-changes-queue.c:    new_item->kind = CHANGE_FILE_MOVED;
libcaja-private/caja-file-changes-queue.c:                            && change->kind != CHANGE_FILE_MOVED
libcaja-private/caja-file-changes-queue.c:                            && change->kind != CHANGE_FILE_MOVED;
libcaja-private/caja-file-changes-queue.c:        case CHANGE_FILE_MOVED:
```

2022-08-05 09:31 UTC, echo083 commented
@rbuj If you don't agree you can dismiss my pull request! Thanks

2022-08-05 09:49 UTC, rbuj commented
@echo083 it's just my opinion, other team members may find your proposal useful or may point you to a better solution. Or you can find another solution that doesn't go through the indirect removal of an operation kind.

2022-08-19 00:29 UTC, lukefromdc commented
closing this as it makes caja too heavy

2022-08-19 00:29 UTC, closed without merging